; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "My application"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "My company, Inc."
!define PRODUCT_WEB_SITE "http://www.mycompany.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\SimulationTicketingSystem_ShenzhenMetro.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\SimulationTicketingSystem_ShenzhenMetro.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\My application"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "..\dependency\src\D3Dcompiler_47.dll"
  SetOutPath "$INSTDIR\generic"
  File "..\dependency\src\generic\qtuiotouchplugin.dll"
  SetOutPath "$INSTDIR\iconengines"
  File "..\dependency\src\iconengines\qsvgicon.dll"
  SetOutPath "$INSTDIR\imageformats"
  File "..\dependency\src\imageformats\qgif.dll"
  File "..\dependency\src\imageformats\qico.dll"
  File "..\dependency\src\imageformats\qjpeg.dll"
  File "..\dependency\src\imageformats\qsvg.dll"
  SetOutPath "$INSTDIR\networkinformation"
  File "..\dependency\src\networkinformation\qnetworklistmanager.dll"
  SetOutPath "$INSTDIR"
  File "..\dependency\src\opengl32sw.dll"
  SetOutPath "$INSTDIR\platforms"
  File "..\dependency\src\platforms\qwindows.dll"
  SetOutPath "$INSTDIR"
  File "..\dependency\src\Qt6Core.dll"
  File "..\dependency\src\Qt6Gui.dll"
  File "..\dependency\src\Qt6Network.dll"
  File "..\dependency\src\Qt6Sql.dll"
  File "..\dependency\src\Qt6Svg.dll"
  File "..\dependency\src\Qt6Widgets.dll"
  File "..\dependency\src\SimulationTicketingSystem_ShenzhenMetro.exe"
  CreateDirectory "$SMPROGRAMS\My application"
  CreateShortCut "$SMPROGRAMS\My application\My application.lnk" "$INSTDIR\SimulationTicketingSystem_ShenzhenMetro.exe"
  CreateShortCut "$DESKTOP\My application.lnk" "$INSTDIR\SimulationTicketingSystem_ShenzhenMetro.exe"
  SetOutPath "$INSTDIR\sqldrivers"
  File "..\dependency\src\sqldrivers\qsqlibase.dll"
  File "..\dependency\src\sqldrivers\qsqlite.dll"
  File "..\dependency\src\sqldrivers\qsqlmimer.dll"
  File "..\dependency\src\sqldrivers\qsqlmysql.dll"
  File "..\dependency\src\sqldrivers\qsqloci.dll"
  File "..\dependency\src\sqldrivers\qsqlodbc.dll"
  File "..\dependency\src\sqldrivers\qsqlpsql.dll"
  SetOutPath "$INSTDIR\styles"
  File "..\dependency\src\styles\qmodernwindowsstyle.dll"
  SetOutPath "$INSTDIR\tls"
  File "..\dependency\src\tls\qcertonlybackend.dll"
  File "..\dependency\src\tls\qschannelbackend.dll"
  SetOutPath "$INSTDIR\translations"
  File "..\dependency\src\translations\qt_ar.qm"
  File "..\dependency\src\translations\qt_bg.qm"
  File "..\dependency\src\translations\qt_ca.qm"
  File "..\dependency\src\translations\qt_cs.qm"
  File "..\dependency\src\translations\qt_da.qm"
  File "..\dependency\src\translations\qt_de.qm"
  File "..\dependency\src\translations\qt_en.qm"
  File "..\dependency\src\translations\qt_es.qm"
  File "..\dependency\src\translations\qt_fa.qm"
  File "..\dependency\src\translations\qt_fi.qm"
  File "..\dependency\src\translations\qt_fr.qm"
  File "..\dependency\src\translations\qt_gd.qm"
  File "..\dependency\src\translations\qt_he.qm"
  File "..\dependency\src\translations\qt_hr.qm"
  File "..\dependency\src\translations\qt_hu.qm"
  File "..\dependency\src\translations\qt_it.qm"
  File "..\dependency\src\translations\qt_ja.qm"
  File "..\dependency\src\translations\qt_ka.qm"
  File "..\dependency\src\translations\qt_ko.qm"
  File "..\dependency\src\translations\qt_lv.qm"
  File "..\dependency\src\translations\qt_nl.qm"
  File "..\dependency\src\translations\qt_nn.qm"
  File "..\dependency\src\translations\qt_pl.qm"
  File "..\dependency\src\translations\qt_pt_BR.qm"
  File "..\dependency\src\translations\qt_ru.qm"
  File "..\dependency\src\translations\qt_sk.qm"
  File "..\dependency\src\translations\qt_tr.qm"
  File "..\dependency\src\translations\qt_uk.qm"
  File "..\dependency\src\translations\qt_zh_CN.qm"
  File "..\dependency\src\translations\qt_zh_TW.qm"
  ; 创建CostSheet目录并复制Excel文件
  SetOutPath "$INSTDIR\CostSheet"
  File "..\dependency\src\CostSheet\附件1 2025年第一批新线开通线网普通车厢票价表.xlsx"
  File "..\dependency\src\CostSheet\附件2 2025年第一批新线开通线网商务车厢票价表.xlsx"
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\My application\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\My application\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\SimulationTicketingSystem_ShenzhenMetro.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\SimulationTicketingSystem_ShenzhenMetro.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\translations\qt_zh_TW.qm"
  Delete "$INSTDIR\translations\qt_zh_CN.qm"
  Delete "$INSTDIR\translations\qt_uk.qm"
  Delete "$INSTDIR\translations\qt_tr.qm"
  Delete "$INSTDIR\translations\qt_sk.qm"
  Delete "$INSTDIR\translations\qt_ru.qm"
  Delete "$INSTDIR\translations\qt_pt_BR.qm"
  Delete "$INSTDIR\translations\qt_pl.qm"
  Delete "$INSTDIR\translations\qt_nn.qm"
  Delete "$INSTDIR\translations\qt_nl.qm"
  Delete "$INSTDIR\translations\qt_lv.qm"
  Delete "$INSTDIR\translations\qt_ko.qm"
  Delete "$INSTDIR\translations\qt_ka.qm"
  Delete "$INSTDIR\translations\qt_ja.qm"
  Delete "$INSTDIR\translations\qt_it.qm"
  Delete "$INSTDIR\translations\qt_hu.qm"
  Delete "$INSTDIR\translations\qt_hr.qm"
  Delete "$INSTDIR\translations\qt_he.qm"
  Delete "$INSTDIR\translations\qt_gd.qm"
  Delete "$INSTDIR\translations\qt_fr.qm"
  Delete "$INSTDIR\translations\qt_fi.qm"
  Delete "$INSTDIR\translations\qt_fa.qm"
  Delete "$INSTDIR\translations\qt_es.qm"
  Delete "$INSTDIR\translations\qt_en.qm"
  Delete "$INSTDIR\translations\qt_de.qm"
  Delete "$INSTDIR\translations\qt_da.qm"
  Delete "$INSTDIR\translations\qt_cs.qm"
  Delete "$INSTDIR\translations\qt_ca.qm"
  Delete "$INSTDIR\translations\qt_bg.qm"
  Delete "$INSTDIR\translations\qt_ar.qm"
  Delete "$INSTDIR\tls\qschannelbackend.dll"
  Delete "$INSTDIR\tls\qcertonlybackend.dll"
  Delete "$INSTDIR\styles\qmodernwindowsstyle.dll"
  Delete "$INSTDIR\sqldrivers\qsqlpsql.dll"
  Delete "$INSTDIR\sqldrivers\qsqlodbc.dll"
  Delete "$INSTDIR\sqldrivers\qsqloci.dll"
  Delete "$INSTDIR\sqldrivers\qsqlmysql.dll"
  Delete "$INSTDIR\sqldrivers\qsqlmimer.dll"
  Delete "$INSTDIR\sqldrivers\qsqlite.dll"
  Delete "$INSTDIR\sqldrivers\qsqlibase.dll"
  Delete "$INSTDIR\SimulationTicketingSystem_ShenzhenMetro.exe"
  Delete "$INSTDIR\Qt6Widgets.dll"
  Delete "$INSTDIR\Qt6Svg.dll"
  Delete "$INSTDIR\Qt6Sql.dll"
  Delete "$INSTDIR\Qt6Network.dll"
  Delete "$INSTDIR\Qt6Gui.dll"
  Delete "$INSTDIR\Qt6Core.dll"
  Delete "$INSTDIR\platforms\qwindows.dll"
  Delete "$INSTDIR\opengl32sw.dll"
  Delete "$INSTDIR\networkinformation\qnetworklistmanager.dll"
  Delete "$INSTDIR\imageformats\qsvg.dll"
  Delete "$INSTDIR\imageformats\qjpeg.dll"
  Delete "$INSTDIR\imageformats\qico.dll"
  Delete "$INSTDIR\imageformats\qgif.dll"
  Delete "$INSTDIR\iconengines\qsvgicon.dll"
  Delete "$INSTDIR\generic\qtuiotouchplugin.dll"
  Delete "$INSTDIR\D3Dcompiler_47.dll"

  Delete "$SMPROGRAMS\My application\Uninstall.lnk"
  Delete "$SMPROGRAMS\My application\Website.lnk"
  Delete "$DESKTOP\My application.lnk"
  Delete "$SMPROGRAMS\My application\My application.lnk"

  RMDir "$SMPROGRAMS\My application"
  RMDir "$INSTDIR\translations"
  RMDir "$INSTDIR\tls"
  RMDir "$INSTDIR\styles"
  RMDir "$INSTDIR\sqldrivers"
  RMDir "$INSTDIR\platforms"
  RMDir "$INSTDIR\networkinformation"
  RMDir "$INSTDIR\imageformats"
  RMDir "$INSTDIR\iconengines"
  RMDir "$INSTDIR\generic"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd